### ISSUE TITLE
Question: Why Hugo?

### ISSUE THREAD

**Issue by fa7ad** [budgie-desktop/budgie-site#1]
Just wondering why you picked hugo (as opposed to Jekyll, which is natively supported by GitHub)

**Comment by ikeydoherty** [comment]
Budgie website isn't deployed on Github infrastructure, it's deployed on our own. :)

**Comment by fa7ad** [comment]
ah, okay :+1:

**Comment by fa7ad** [comment]
Although, Now I'm wondering what the purpose of the repo is at all :confused:

**Comment by ikeydoherty** [comment]
So that the website is open source and will be open to contribution. It's developed in the open. Once it's ready it'll be what is then deployed to budgie-desktop.org.

**Comment by fa7ad** [comment]
got it
